// <auto-generated />
using BinaryDaysOfWeekApi.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinaryDaysOfWeekApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinaryDaysOfWeekApi.Models.Entities.SchedulerBinaryEncoded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("DaysOfWeek")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchedulerBinaryEncoded", (string)null);
                });

            modelBuilder.Entity("BinaryDaysOfWeekApi.Models.Entities.SchedulerEnum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Friday")
                        .HasColumnType("integer");

                    b.Property<int?>("Monday")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Saturday")
                        .HasColumnType("integer");

                    b.Property<int?>("Sunday")
                        .HasColumnType("integer");

                    b.Property<int?>("Thursday")
                        .HasColumnType("integer");

                    b.Property<int?>("Tuesday")
                        .HasColumnType("integer");

                    b.Property<int?>("Wednesday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SchedulerEnums", (string)null);
                });

            modelBuilder.Entity("BinaryDaysOfWeekApi.Models.Entities.SchedulerStringArray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("DaysOfWeek")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchedulerStringArrays", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
